[project]
name = "quart-data-star-jinja"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datastar-py>=0.6.3",
    "quart>=0.20.0",
]
